API_URL = 'http://192.168.27.1:8081'
MESSAGE_URL = 'http://192.168.27.1:8081'

MIDI_INPUT_DEVICE = 3

RAVELOX_HOST = 'localhost'
RAVELOX_PORT = '5006'

GIG_MESSAGE = 'CONTROLLER_GIG_MESSAGE'
PROGRAM_MESSAGE = 'CONTROLLER_PROGRAM_MESSAGE'
SONG_MESSAGE = 'CONTROLLER_SONG_MESSAGE'
SYNC_MESSAGE = 'CONTROLLER_SYNC_MESSAGE'
PEDAL1_MESSAGE = 'CONTROLLER_PEDAL1_MESSAGE',
PEDAL2_MESSAGE = 'CONTROLLER_PEDAL2_MESSAGE'

VIEW_PROGRAM_MESSAGE = 'VIEW_PROGRAM_MESSAGE'
VIEW_SONG_MESSAGE = 'VIEW_SONG_MESSAGE'

VOLUME_CC = 7
MIN_DELAY = 0.007
MIDI_RECEIVE_DELAY = 0.05
CHANNEL_1_CC = 176
CHANNEL_1_PC = 192
KEEPALIVE_FREQUENCY = 500
KEEPALIVE_CHANNEL = 11
