export const INIT_ALL = 'INIT_ALL'

export const SET_SONGLIST = 'SET_SONGLIST'
export const ADD_SONG = 'ADD_SONG'
export const UPDATE_SONG = 'UPDATE_SONG'
export const ADD_SONG_ITEMS = 'ADD_SONG_ITEMS'
export const UPDATE_SONGPRESET = 'UPDATE_SONGPRESET'
export const REFRESH_SONG = 'REFRESH_SONG'

export const SET_PRESETLIST = 'SET_PRESETLIST'
export const ADD_PRESET = 'ADD_PRESET'
export const UPDATE_PRESET = 'UPDATE_PRESET'

export const SET_INSTRUMENTLIST = 'SET_INSTRUMENTLIST'
export const ADD_INSTRUMENT = 'ADD_INSTRUMENT'
export const UPDATE_INSTRUMENT = 'UPDATE_INSTRUMENT'
export const SET_INSTRUMENT_IMAGE = 'SET_INSTRUMENT_IMAGE'

export const SET_INSTRUMENTBANKLIST = 'SET_INSTRUMENTBANKLIST'
export const ADD_INSTRUMENTBANK = 'ADD_INSTRUMENTBANK'
export const UPDATE_INSTRUMENTBANK = 'UPDATE_INSTRUMENTBANK'

export const SET_GIGLIST = 'SET_GIGLIST'
export const ADD_GIG = 'ADD_GIG'
export const UPDATE_GIG = 'UPDATE_GIG'
export const POPULATE_GIG_SONGS = 'POPULATE_GIG_SONGS'

export const SET_GIGSONGLIST = 'SET_GIGSONGLIST'
export const ADD_GIGSONG = 'ADD_GIGSONG'
export const UPDATE_GIGSONG = 'UPDATE_GIGSONG'

export const SET_CURRENTSONG_ID = 'SET_CURRENTSONG_ID'
export const SET_CURRENT_PROGRAMMIDIPEDAL = 'SET_CURRENT_MIDIPEDAL'
export const SET_CURRENTGIG_ID = 'SET_CURRENTGIG_ID'

export const SOCKET_VIEW_PROGRAM_MESSAGE = 'SOCKET_VIEW_PROGRAM_MESSAGE'
export const SOCKET_VIEW_SONG_MESSAGE = 'SOCKET_VIEW_SONG_MESSAGE'

export const SOCKET_CONTROLLER_PROGRAM_MESSAGE = 'SOCKET_CONTROLLER_PROGRAM_MESSAGE'
export const SOCKET_CONTROLLER_SONG_MESSAGE = 'SOCKET_CONTROLLER_SONG_MESSAGE'
export const SOCKET_CONTROLLER_SYNC_MESSAGE = 'SOCKET_CONTROLLER_SYNC_MESSAGE'
