export const SET_SONGLIST = 'SET_SONGLIST'
export const ADD_SONG = 'ADD_SONG'
export const UPDATE_SONG = 'UPDATE_SONG'

export const SET_PRESETLIST = 'SET_PRESETLIST'
export const ADD_PRESET = 'ADD_PRESET'
export const UPDATE_PRESET = 'UPDATE_PRESET'

export const SET_INSTRUMENTLIST = 'SET_INSTRUMENTLIST'
export const ADD_INSTRUMENT = 'ADD_INSTRUMENT'
export const UPDATE_INSTRUMENT = 'UPDATE_INSTRUMENT'

export const SET_INSTRUMENTBANKLIST = 'SET_INSTRUMENTBANKLIST'
export const ADD_INSTRUMENTBANK = 'ADD_INSTRUMENTBANK'
export const UPDATE_INSTRUMENTBANK = 'UPDATE_INSTRUMENTBANK'
